feat(tags): Adding the ability to tag tasks for filtering on index
Shopify/maintenance_tasks pull request #815
Opened 2023-04-29 05:16 UTC by lawrencewong

- In our team's usage of maintenance tasks we found that with the additions of new tasks, and previous runs displaying raw data it made it difficult to find specific tasks.
- We wanted a way to be able to group certain tasks either by domain or usage.
- Adding the ability to filter by using links defined by tags on the tasks.
- If there are tags assigned to any task, it will be listed at the top of the index page. The tags are links to the tasks controller with a parameter of the selected tag. This will only surface tasks that have the given tag.

- TODO for PR, update README

When no tasks have assigned tags:
<img width="1273" alt="Screenshot 2023-04-29 at 12 16 26 AM" src="https://user-images.githubusercontent.com/3063931/235284886-7d0229bf-95b3-4f06-a9b6-aa601ace0cd8.png">

When tasks have assigned tags:
<img width="1158" alt="Screenshot 2023-04-29 at 12 15 40 AM" src="https://user-images.githubusercontent.com/3063931/235284899-afe1011b-f8c3-4a46-ac1c-47c581d2dae0.png">

Demo:
https://user-images.githubusercontent.com/3063931/235284910-65f7fd35-a18f-4214-b7e9-8b7f3efe3035.mov

2023-05-01 13:34 UTC, desheikh commented on app/controllers/maintenance_tasks/tasks_controller.rb
> +      tag = params[:tag] || nil
nil should be the default here

2023-05-01 13:35 UTC, desheikh commented on app/controllers/maintenance_tasks/tasks_controller.rb
> +      tag = params[:tag] || nil
```suggestion
      tag = params[:tag]
```

params[:tag] will be nil if nothing is passed in

2023-05-01 13:37 UTC, desheikh commented on app/helpers/maintenance_tasks/tasks_helper.rb
> +      MaintenanceTasks::Task.available_tasks.map(&:tags).flatten.uniq
We should memoize the result here

2024-01-19 05:13 UTC, gmcgibbon requested changes
As discussed in the issue. We seem to be more open to grouping by task module / nesting. Can we please take that direction instead?

2024-02-13 23:34 UTC, gmcgibbon commented
Thanks for your contribution, but I'm closing this because there's no recent activity. If you're still interested in working on this feature, please open another PR.

2024-02-13 23:34 UTC, closed without merging